name: CI

on:
    push:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                emacs-version: [28.2]
                experimental: [false]
                include:
                    - emacs-version: snapshot
                      experimental: true

        steps:
            - uses: purcell/setup-emacs@master
              with:
                  version: ${{ matrix.emacs-version }}

            - uses: actions/checkout@v3

            - name: test
              run: ./test-startup.sh
